Task 2
IvanchenkoSA/MoneyTransfer pull request #1
Opened 2023-07-19 10:33 UTC by IvanchenkoSA

2023-07-19 10:41 UTC, jukov requested changes

2023-07-19 10:41 UTC, jukov commented on src/main/kotlin/Main.kt
> +    val mir = CardType("Мир")
CardType можно сделать enum class и в него всунуть все типы карт.
Тогда условия в when в getComission станут в 2 раза короче

2023-07-19 10:41 UTC, jukov commented on src/main/kotlin/Main.kt
> +    val user3 = User("Ivan", 46980, 29, vkPay)
Не понимаю что такое 32, 23, 29. Добавь имена к аргументам
<img width="636" alt="image" src="https://github.com/IvanchenkoSA/MoneyTransfer/assets/8081721/243d3de8-3970-4337-a128-792dadac5d66">

2023-07-19 10:41 UTC, jukov commented on src/main/kotlin/Main.kt
> +    fun getComission(cardType: CardType, totalSum: Int, amountTransfer: Int): Number? {
Этот метод должен возвращать `Double?`

2023-07-19 10:41 UTC, jukov commented on src/main/kotlin/Main.kt
> +                else -> null
Мне лень разбираться что тут считается, упакуй все вхождения в when в скобки, потом сделай переносы строк или дополнительные переменные так чтобы каждая строка была не длиннее 120 символов
<img width="734" alt="image" src="https://github.com/IvanchenkoSA/MoneyTransfer/assets/8081721/0be41c4a-a899-4191-92c6-ff7620fd77c0">

2023-07-19 13:00 UTC, jukov requested changes

2023-07-19 13:00 UTC, jukov commented on src/main/kotlin/Main.kt
> +            (amountTransfer + totalSum in 0..75000)
- можно просто `(amountTransfer + totalSum) > =  75000 ->`
- перенос строки лишний, стрелка обычно на той же строке где условие
- скобки вокруг условия не нужны

2023-07-19 13:00 UTC, jukov commented on src/main/kotlin/Main.kt
> +                })?.toDouble()
А зачем вложеный when? Вынеси его условия наружу во внешний when

2023-07-19 13:00 UTC, jukov commented on src/main/kotlin/Main.kt
> +                    (cardType == CardType.MASTERCARD) or (cardType == CardType.MAESTRO)
Вместо `or` `||`, скобки вокруг сравнений не нужны

2023-07-19 13:00 UTC, jukov commented on src/main/kotlin/Main.kt
> +                (when {
Скобки вокруг when не нужны

2023-07-19 13:00 UTC, jukov commented on src/main/kotlin/Main.kt
> +                    else ((amountTransfer / 100) * 0.6 + 20)
Если if else полностью не влезает в одну строку, то лучше использовать скобки внутри

2023-07-20 08:17 UTC, jukov commented on src/main/kotlin/Main.kt
> +            else 0.toDouble()
Тут тоже if на нескольких строках

2023-07-20 08:17 UTC, jukov commented on src/main/kotlin/Main.kt
> +        }
Возьми за основу вот такой when, заполни его условиями специфичными для каждой карты.

```
    when (cardType) {
        CardType.VKPAY -> {
            
        }

        CardType.MASTERCARD,
        CardType.MAESTRO -> {

        }

        CardType.VISA,
        CardType.MIR -> {

        }
    }
```

Если я правильно понял, то есть какое-то условие общее для всех карт, типа если больше 600к, то перевод невозможен. 

Но, я не уверен, в этой версии определенно есть баг, потому что у тебя все переводы меньше 75000 падают в первый бранч when и проверяются на VKPAY, то есть для других типов карт вернется 0.
В прошлой версии было условие
`(amountTransfer + totalSum in 0..75000) -> if (totalSum + amountTransfer > 600000) null else 0`. 
В него падали все переводы, т.е. для всех карт комиссия должна была выходить 0.

Короче говоря, если есть такое условие, то перед when напиши if и проверь его отдельно для всех карт и используя `return` сразу верни `null` не доходя до `when`.

2023-07-20 08:17 UTC, jukov commented on src/main/kotlin/Main.kt
> +    fun getComission(cardType: CardType, totalSum: Int, amountTransfer: Int): Double? {
А зачем сюда передается cardType если этот метод и так имеет к нему доступ?

2023-07-20 08:17 UTC, jukov commented on src/main/kotlin/Main.kt
> +            else 0.toDouble()
Тут вроде не нужен else

2023-07-20 11:13 UTC, jukov requested changes

2023-07-20 11:13 UTC, jukov commented on src/main/kotlin/Main.kt
> +                } else{
ctrl alt l

2023-07-20 11:13 UTC, jukov commented on src/main/kotlin/Main.kt
> +            }?.toDouble()
если задашь minSum = 35.0, то не будет необходимости конвертировать здесь в double

2023-07-20 11:13 UTC, jukov commented on src/main/kotlin/Main.kt
> +            }
Переделай остальные кейсы по аналогии с тем как я переделал этот

```
CardType.MASTERCARD, CardType.MAESTRO -> {
    val exceedMinSum = amountTransfer + totalSum >= 75000
    val lessThanMaxSum = amountTransfer < lowLim || totalSum + amountTransfer < lim
    
    if (exceedMinSum && lessThanMaxSum) {
        amountTransfer / 100 * 0.6 + 20
    } else {
        null
    }
}
```

2023-07-20 11:14 UTC, jukov commented
Я зарезолвил всё исправленные замечания. Ко всем оставшимся пожалуйста напиши коммент когда исправишь их, можешь расписать что конкретно сделал если считаешь необходимым

2023-07-20 13:44 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +                    else ((amountTransfer / 100) * 0.6 + 20)
исправил

2023-07-21 08:28 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +                    else ((amountTransfer / 100) * 0.6 + 20)
Исправил👍

2023-07-21 08:28 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +                (when {
убрал 👍

2023-07-21 08:28 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +                    (cardType == CardType.MASTERCARD) or (cardType == CardType.MAESTRO)
поменял 👍

2023-07-21 08:29 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +                })?.toDouble()
вынес 👍

2023-07-21 08:29 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +            (amountTransfer + totalSum in 0..75000)
исправил👍

2023-07-21 08:30 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +    fun getComission(cardType: CardType, totalSum: Int, amountTransfer: Int): Double? {
убрал👍

2023-07-21 08:31 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +            }?.toDouble()
сделал👍

2023-07-21 11:04 UTC, jukov commented on src/main/kotlin/Main.kt
> +                } else null
```
if () {
...
} else {
...
}
```

или 

`if () ... else ...`

2023-07-21 11:04 UTC, jukov commented on src/main/kotlin/Main.kt
> +                }
Первое условие true если меньше 75к, второе условие true если меньше 150к, чето тут лишнее кажется

2023-07-21 11:04 UTC, jukov commented on src/main/kotlin/Main.kt
> +                val exceedMinSum = (amountTransfer / 100) * 0.75 < minSum
Название скопировано из верхнего кейса, хотя тут уже комиссия проверяется а не сумма, я думаю нужно другое название

2023-07-21 11:04 UTC, jukov commented on src/main/kotlin/Main.kt
> +                }
Можно перепаковать так

```
if (lessThanMaxSum) {
    if (exceedMinSum) {
        ...
    } else {
        ...
    }
} else {
    return 0.0
}
```

2023-07-21 12:13 UTC, jukov commented
апрув

2023-07-21 12:17 UTC, merged