added Attachments
IvanchenkoSA/MoneyTransfer pull request #3
Opened 2023-08-15 13:27 UTC by IvanchenkoSA

2023-08-15 14:11 UTC, jukov commented
Вот эти коммиты тоже должны быть в этом пуллреквесте
<img width="817" alt="image" src="https://github.com/IvanchenkoSA/MoneyTransfer/assets/8081721/3198b812-d255-49a9-a474-631ecc6143a9">

2023-08-17 12:37 UTC, jukov requested changes

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +class WallService {
Вынеси этот класс в отдельный файл

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +class PostNotFoundException(message: String): RuntimeException(message)
Вынеси этот класс в отдельный файл

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +        if (index == -1) throw PostNotFoundException("Post not found") else{
1. Ctrl+Alt+L. Перед каждым коммитом просматривай все внесенные изменения и если видишь такое, нужно фиксить.
2. Если скобка есть в else, она должна быть в if. Или без скобок вообще
3. else тут вообще не нужен, т.к. после throw ты и так выйдешь из функции

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +data class Post(
В отдельный файл.
Все классы которые используются как часте модели поста (включены в этот класс) нужно вынести в этот же файл. Я говорю о классах Reposts, PostSource, Likes и т.д.

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +interface Attachments{
Название класса в единственном числе

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +    val count: Int, val userLikes: Boolean, val canLikes: Boolean, val canPublish: Boolean
Каждое поле на новой строке

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +    val attachments: Array<Attachments> = emptyArray()
Почему здесь используется массив, а в copyHistory используется list?

2023-08-17 12:37 UTC, jukov commented on src/main/kotlin/Post.kt
> +    val count: Int, val userLikes: Boolean, val canLikes: Boolean, val canPublish: Boolean
canLike

2023-08-17 12:37 UTC, jukov commented on src/test/kotlin/ru/netology/WallServiceTest.kt
> +import org.junit.Assert.*
Здесь ассерты из Junit, а в UserTest из kotlin.test. Выбери одни и используй везде

2023-08-17 12:37 UTC, jukov commented on src/test/kotlin/ru/netology/WallServiceTest.kt
> +        println(isExisting)
Убери все принты из тестов, то что тебе нужно было для дебага не должно попадать в общую кодобазу

2023-08-17 15:24 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +class WallService {
Сделал

2023-08-17 15:24 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +class PostNotFoundException(message: String): RuntimeException(message)
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +        if (index == -1) throw PostNotFoundException("Post not found") else{
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +data class Post(
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +interface Attachments{
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +    val count: Int, val userLikes: Boolean, val canLikes: Boolean, val canPublish: Boolean
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +    val attachments: Array<Attachments> = emptyArray()
Поменял

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +    val count: Int, val userLikes: Boolean, val canLikes: Boolean, val canPublish: Boolean
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/test/kotlin/ru/netology/WallServiceTest.kt
> +import org.junit.Assert.*
Сделал

2023-08-17 15:25 UTC, IvanchenkoSA commented on src/test/kotlin/ru/netology/WallServiceTest.kt
> +        println(isExisting)
Убрал

2023-08-17 18:17 UTC, jukov requested changes

2023-08-17 18:17 UTC, jukov commented on src/main/kotlin/WallService.kt
> +        posts += post.copy(id = id)
На каждый вызов += создается новый массив, содержащий все предыдущие элементы и новый элемент. Это не эффиктивно. 
Везде где ты работаешь с потенциально неограниченным списком данных переделай на ArratList.

2023-08-17 18:17 UTC, jukov commented on src/main/kotlin/WallService.kt
> +        if (index == -1) return false else {
А почему у тебя здесь false отдается если пост не нашелся, а выше exception кидается?
Модные пацаны это называют "неконсистентно", по факту просто когда неодинаково то глаз за это цепляется, да и просто работать сложнее с такими классами.

2023-08-17 22:30 UTC, IvanchenkoSA commented on src/main/kotlin/WallService.kt
> +        posts += post.copy(id = id)
переделал

2023-08-17 22:30 UTC, IvanchenkoSA commented on src/main/kotlin/WallService.kt
> +        if (index == -1) return false else {
исправил

2023-08-18 10:45 UTC, jukov requested changes

2023-08-18 10:45 UTC, jukov commented on src/main/kotlin/WallService.kt
> +    private var posts = emptyList<Post>().toMutableList()
mutableListOf() или ArrayList() здесь

2023-08-18 10:45 UTC, jukov commented on src/main/kotlin/WallService.kt
> +        comments += comment
Та же проблема, на каждый вызов будет создаваться лист. Поэтому нужен mutable list

2023-08-18 10:45 UTC, jukov commented on src/main/kotlin/WallService.kt
> +        if (index == -1) return false else {
Можно boolean теперь не возвращать из этого метода, раз ты exception кидаешь

2023-08-18 13:50 UTC, IvanchenkoSA commented on src/main/kotlin/WallService.kt
> +    private var posts = emptyList<Post>().toMutableList()
ArrayList()

2023-08-18 14:05 UTC, merged