Added Note Service
IvanchenkoSA/MoneyTransfer pull request #4
Opened 2023-08-22 11:49 UTC by IvanchenkoSA

2023-08-22 12:34 UTC, jukov requested changes

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/Main.kt
> +    val ns = NoteServiceImplements()
NoteServiceImpl, Impl это общепринятое окончание для имплементаций интерфейсов

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/Note.kt
> +        }
А зачем специальный кейс когда нет комментов? Вроде ничего не свалится если их не будет, а то что нет комментов это тоже полезная информация, можно явно показать

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +        notes += note
А почему для нотсов id тут не проставляется как для постов и комментов?
Заведи отдельно postId и commentId выше, и здесь так же переназначай id как в других местах.

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +        notes.forEach { i -> println("$i ") }
println(notes.joinToString())

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +        comment.id += id
Просто =

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +        val index = notes.indexOfFirst { note -> note.id == noteId }
Можно не ебаться с индексами и просто найти сразу note через find как было сделаоно ниже.
Проверка на наличие нотса тут потерялась еще

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +        comment.id += id
можно сразу comment.id = id++

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun deleteNote(noteId: Int): Int {
Почему здесь возвращаемый тип int? Что должно возвращаться?

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +                ?: throw NotFoundException("Comment not found")
```
notes.find { note -> note.id == noteId }
    ?.comments
    ?.find { comment -> comment.id == commentId }
    ?: throw NotFoundException("Comment not found")
```

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +                ?: throw NotFoundException("Comment not found")
```
notes.find { note -> note.id == noteId }
    ?.comments
    ?.find { comment -> comment.id == commentId }
    ?: throw NotFoundException("Comment not found")
```

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +            notes[index].comments[indexComment].copy(text = comment.text)
В целом неважно пользуешься ты indexOfFirst или find, но вот здесь это реально душно выглядит, проще так:

```
val comment: Comment = notes
    .find { note -> note.id == noteId }
    ?.comments
    ?.find { comment -> comment.id == commentId }
    ?: throw NotFoundException("Comment not found")

comment = comment.copy(text = newText)
```

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun editComment(noteId: Int, commentId: Int, comment: Comment) {
Опять та же хуйня с интерфейсом. Почему в editNote передается отдельно title и text, а сюда целый коммент? Передавай отдельно text и всё

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun getNoteById(noteId: Int) {
Это скорее printNoteById. Надо или переименовать метод или возвращать Note и по месту вызова делать println

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun getNoteComments(noteId: Int) {
Тоже print или вернуть коммент

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/Post.kt
> +    val text: String?,
А почему text nullable? Не бывает же заметок без текста

2023-08-22 12:34 UTC, jukov commented on src/main/kotlin/Post.kt
Файл называется пост, а в нем коммент

2023-08-22 12:34 UTC, jukov commented
Ну и тесты тоже можно написать

2023-08-23 11:57 UTC, IvanchenkoSA commented on src/main/kotlin/Main.kt
> +    val ns = NoteServiceImplements()
поменял

2023-08-23 11:57 UTC, IvanchenkoSA commented on src/main/kotlin/Note.kt
> +        }
убрал

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +        notes += note
завел

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +        notes.forEach { i -> println("$i ") }
+

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +        comment.id += id
поменял

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun editComment(noteId: Int, commentId: Int, comment: Comment) {
поменял

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun getNoteById(noteId: Int) {
изменил

2023-08-23 11:58 UTC, IvanchenkoSA commented on src/main/kotlin/NoteServiceImplements.kt
> +    override fun getNoteComments(noteId: Int) {
ага

2023-08-23 11:59 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
> +    val text: String?,
🤔 согласен

2023-08-23 12:00 UTC, IvanchenkoSA commented on src/main/kotlin/Post.kt
🤔🤔🤔🤔🤔

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        note.id += noteId
просто =

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +    }
Я думаю что раз ты внизу сделал геттеры и убрал принты, то здесь тоже можно убрать принт чтобы у этого класса не было ответственности за вывод на экран, только за жонглирование нотсами и комментами.

Я имею ввиду заменить этот метод на getNotes(), возвращать список заметок и уже тот класс который использует NoteService будет делать с этими заметками че хочет, в данном случае выводить на экран.

Причем getNotes() будет как раз возвращать List, а не ArrayList. Потому что у клиента этого класса не должно быть возможности редактировать заметки, только читать

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        return 1
ты же вроде commentId хотел возвращать

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        return 1
То же самое что и с deleteComment

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        return 1
То же самое что и с deleteComment

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        return 1
То же самое что и с deleteComment

2023-08-24 10:03 UTC, jukov commented on src/main/kotlin/NoteServiceImpl.kt
> +        return 1
На самом деле ничего не надо возвращать.

Проблема же была в том что тесты писать неудобно? Вот теперь у тебя есть функции getNoteById и getNoteComments. Можешь их в тестах вызывать, искать те комменты которые ты редактировал и проверять что они в том состоянии которое ты ожидаешь

2023-08-27 10:08 UTC, jukov commented on src/test/kotlin/NoteServiceImplTest.kt
> +        val result = ns.createComment(note.id, comment)
Мне не нравится то что ты во всех тестах ожидаешь что у тебя в note.id лежит правильный id.
Он туда кладется неявно. Обычно в таких сервисах обычно данные уходят на бэк и id присваивается там, и тебе в ответе от бэка либо возвращают этот id, либо возвращают новый объект, то есть в том объекте который ты отдал в addNote ничего меняться не будет в этом случае.

Я предлагаю переделать addNote так чтобы он принимал title и text, а возвращал id.

Если лень можешь не делать

2023-08-27 10:09 UTC, jukov approved these changes

2023-10-15 16:59 UTC, merged